### ISSUE TITLE
Les options custom ne marche plus avec la version 2.0.0

### ISSUE THREAD

**Issue by celinechamiot** [stimulus-components/stimulus-carousel#1]
Bonjour, 

Je constate un soucis sur la dernière version du package, les options ```data-carousel-options``` plus pris en compte, uniquement les paramètres globaux dans le controller ici:

```
import Carousel from "stimulus-carousel"

export default class extends Carousel {
  get defaultOptions () {
    return {
      slidesPerView: 4.2,
      spaceBetween: 10,
      grabCursor: true
    }
  }
}
```

Exemple qui marche quand le rollback en  1.0.2 et plus avec 2.0.0:

```
.swiper-container.slider-navigation.pb-13(data-controller="carousel" data-carousel-options="{  'freeMode': false, 'slidesPerView': 1, 'pagination': { 'el': '.swiper-pagination', 'dots': true, 'centerMode': true, 'clickable': true }, 'navigation': { 'nextEl': '.swiper-button-next', 'prevEl': '.swiper-button-prev' }, 'navigation': { 'nextEl': '.swiper-button-next', 'prevEl': '.swiper-button-prev' } }")
  .swiper-wrapper
    .swiper-slide 1
    .swiper-slide 2
              ....

  .swiper-pagination
  .swiper-button-next
  .swiper-button-prev
```
 
Merci pour la réponse !

**Comment by guillaumebriday** [comment]
Hello 👋 

Il faut utiliser Stimulus 2.0 pour utiliser ce package dans sa version 2.0 👍  Si tu utilises Stimulus < 2, il faut effectivement rester sur la version 1.x de ce package

C'est un breaking change 👉https://github.com/stimulus-components/stimulus-carousel/blob/master/CHANGELOG.md#200---2020-12-05
