### ISSUE TITLE
Doesn't play well with bootstrap

### ISSUE THREAD

**Issue by tacman** [stimulus-components/stimulus-carousel#12]
The demo works fine until I add bootstrap.  The libraries are loaded via an importmap (as esm modules), I suspect the problem is with swiper.js but I don't know.
 
I've set up a really simple Symfony demo that shows the problem
```
git clone git@github.com:survos-sites/carousel-demo.git && cd carousel-demo
composer install
bin/console importmap:install
symfony server:start -d
symfony open:local
```

If you open assets/app.js and remove the lines that load the bootstrap js and css, the arrows work.

Slightly more details in the README at https://github.com/survos-sites/carousel-demo

**Comment by guillaumebriday** [comment]
If it's still an issue, please reopen it in the main repo: https://github.com/stimulus-components/stimulus-components
