### ISSUE TITLE
Typescript error: SwiperOptions is not imported correctly

### ISSUE THREAD

**Issue by mkrauser** [stimulus-components/stimulus-carousel#13]
Hey there,

the import for SwiperOptions is not correct (see https://github.com/stimulus-components/stimulus-carousel/blob/99f051655f495dd378dda15c6f7d1f165e376e1e/src/index.ts#L2)

It needs to look like this:

```
import { SwiperOptions } from "swiper/types"
```

Thank you, for your work on this!

**Comment by guillaumebriday** [comment]
If it's still an issue, please reopen it in the main repo: https://github.com/stimulus-components/stimulus-components
