### ISSUE TITLE
Module not found: Error: Can't resolve 'swiper/bundle' in 'stimulus-carousel/dist'

### ISSUE THREAD

**Issue by PhilippMeissner** [stimulus-components/stimulus-carousel#3]
Here's the error message that pops up

```
ERROR in ./node_modules/stimulus-carousel/dist/stimulus-carousel.es.js
Module not found: Error: Can't resolve 'swiper/bundle' in '/Users/foobar/zeit/project/node_modules/stimulus-carousel/dist'
resolve 'swiper/bundle' in '/Users/foobar/zeit/project/node_modules/stimulus-carousel/dist'
  Parsed request is a module
  using description file: /Users/foobar/zeit/project/node_modules/stimulus-carousel/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
    .....
```

```
// index.js
import Carousel from "stimulus-carousel";

const application = Application.start();
application.register("carousel", Carousel);
...
```

```
// application.scss
...
@import "~swiper/swiper-bundle";
...
```

It simply fails to compile.

Running
- Node 15.14.x
- stimulus-carousel 3.0.0
- stimulus 2.0.0
- rails 6.1.4.x

**Comment by schnika** [comment]
Looks like https://github.com/stimulus-components/stimulus-carousel/blob/master/src/index.ts#L4 cannot get resolved properly.

I think the import should be changed to `import Swiper from "swiper/swiper-bundle";`;

**Comment by guillaumebriday** [comment]
Hum I use the new exports options from `package.json` and according to the documentation the syntax is correct https://swiperjs.com/get-started

Check https://swiperjs.com/migration-guide#node-es-modules

I will try to use the default import syntax as @schnika suggested

**Comment by PhilippMeissner** [comment]
I can confirm this issue was introduced with Swiper 7.x, it seems to be working fine with Swiper 6.x

**Comment by ernsheong** [comment]
Is there a resolution for this? A blocker

**Comment by guillaumebriday** [comment]
I updated the documentation, at this moment I managed to import CSS with JS https://stimulus-components.netlify.app/docs/stimulus-carousel/#before-starting

**Comment by netelix** [comment]
According to @PhilippMeissner, I had to manually install swiper 6 to have stimulus carousel working.
Thanks for the tips
