### ISSUE TITLE
Cannot find module 'swiper/bundle'

### ISSUE THREAD

**Issue by ernsheong** [stimulus-components/stimulus-carousel#4]
I'm sorry I need a bit of help. I followed the guide at https://stimulus-components.netlify.app/docs/stimulus-carousel/

But I get the following error:
![image](https://user-images.githubusercontent.com/1343284/144989168-f88b04f2-163e-46a0-a872-9ac4eb0e197d.png)

![image](https://user-images.githubusercontent.com/1343284/144989194-432f93d1-5097-42f6-88a2-c5211070e949.png)

Any help?

(New Rails 6 project, NPM 3.0.0 stimulus-carousel)

![image](https://user-images.githubusercontent.com/1343284/144989690-bc421c08-b152-44f7-bca1-eeaa2a8a12e6.png)

**Comment by TazzyG** [comment]
I also have the same error following the same guidelines.

**Comment by ernsheong** [comment]
I haven’t tried, but it looks like swiper is a peer dependency and has to
be installed separately.

**Comment by ztcollazo** [comment]
Have you tried `import 'swiper/css/bundle'`?

**Comment by guillaumebriday** [comment]
@ztcollazo I updated the documentation with this solution 👍

**Comment by ernsheong** [comment]
I think this is unresolved. You are importing from "swiper/bundle" directly:

![image](https://user-images.githubusercontent.com/1343284/147874263-83ecab28-1090-45a8-b2df-9f334073460a.png)
https://github.com/stimulus-components/stimulus-carousel/blob/7dec66ec57b4bb8f4b4eb551fce5401618648e5f/src/index.ts#L4

And using Vite to resolve it:

![image](https://user-images.githubusercontent.com/1343284/147874287-618b98af-3849-44a0-a1a7-f7a0f867b475.png)

swiper/bundle doesn't exist in my node_modules:

![image](https://user-images.githubusercontent.com/1343284/147874300-e64dcde5-6c2d-4190-8899-782d9624cb03.png)

Hence error:

![image](https://user-images.githubusercontent.com/1343284/147874312-271dba8d-3d3b-420d-8a4b-3505453258f1.png)

So for most of us it will fail unless we define "swiper/bundle" globally, but this is a poor approach?

**Comment by ztcollazo** [comment]
You might be able to try extending the controller and overriding the swiper instance with a new instance that is imported from `'swiper'` instead of `'swiper/bundle'`.

**Comment by belumarek** [comment]
hey guys the solution given by @guillaumebriday its not working, someone got the answer?

**Comment by bstst** [comment]
Had the same issue. Got it working on my rails app with this (`environment.js`), which should also work for other webpack environments:

```
const { environment } = require('@rails/webpacker');

const webpack = require('webpack');

environment.plugins.append(
  'NormalReplace',
  new webpack.NormalModuleReplacementPlugin(/swiper\/bundle/, 'swiper/swiper-bundle')
);

module.exports = environment;
```
